version: '3.8'

services:
  cafeapp:
    build:
      context: ./ 
      dockerfile: Dockerfile
    image: sthuthi22/mompopcafeapp:latest
    container_name: mompopcafeapp     
    ports:
      - "5001:80"  # Change port if necessary
    depends_on:
      - mysql
        #volumes:
        #- admin_data:/path/to/admin_service/data


  mysql:
    image: mysql:latest
    container_name: mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Msois@123  
      MYSQL_DATABASE: mom_pop_db 
        #MYSQL_USER: root 
      MYSQL_PASSWORD: Msois@123  
    ports:
      - "3307:3306"  # Change port if necessary
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mompopdb/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql

volumes:
  #admin_data:
  #faculty_data:
  #student_data:
  mysql_data:
